require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

#Check that models subclass ApplicationRecord.
Rails/ApplicationRecord:
  Enabled: false

LineLength:
  Max: 99

Style/ExpandPathArguments:
  Enabled: false

Metrics/BlockLength:
  Max: 40
