development:
  mailer_user_name: <%= ENV['USER_NAME'] %>
  mailer_password: <%= ENV['PASSWORD'] %>
  mailer_address: <%= ENV['ADDRESS'] %>
  mailer_domain: <%= ENV['DOMAIN'] %>
  mailer_port: <%= ENV['PORT'] %>
